import fs from "node:fs/promises";
import path from "node:path";
import openapiTS, { astToString } from "openapi-typescript";
import type { ApiGenerateClient } from "@blissful-infra/shared";

export async function generateTypescriptClient(
  specPath: string,
  config: ApiGenerateClient,
  projectDir: string,
  dryRun = false
): Promise<void> {
  const absSpec = path.resolve(projectDir, specPath);
  const absOut = path.resolve(projectDir, config.output);

  if (dryRun) {
    console.log(`  [dry-run] typescript client: ${specPath} → ${config.output}/`);
    return;
  }

  await fs.mkdir(absOut, { recursive: true });

  // Generate TypeScript type definitions from OpenAPI spec
  const ast = await openapiTS(new URL(`file://${absSpec}`));
  const typesSource = astToString(ast);
  await fs.writeFile(path.join(absOut, "index.ts"), typesSource, "utf8");

  // Generate a typed fetch client wrapper that uses openapi-fetch
  const clientSource = buildClientWrapper();
  await fs.writeFile(path.join(absOut, "client.ts"), clientSource, "utf8");
}

function buildClientWrapper(): string {
  return `// Generated by blissful-infra generate — do not edit manually
// Re-run \`blissful-infra generate\` after changing openapi.yaml

import createClient from "openapi-fetch";
import type { paths } from "./index.js";

export const client = createClient<paths>({ baseUrl: "/" });

export type { paths };
`;
}
